name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Build
        run: cargo build --release --verbose
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: true
          title: "Release Build linux"
          files: |
            target/release/luana
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: ./target/debug/luana
  build-windows:

    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Build
        run: cargo build --release --verbose
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-win32"
          prerelease: true
          title: "Release Build win32"
          files: |
            target/release/luana.exe
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: ./target/debug/luana